// Country dial codes with national significant number (NSN) length ranges.
// `len: [min, max]` counts the digits a customer types AFTER the dial code,
// with any leading trunk 0 stripped. Used by checkout to let expats check out
// with any country's number while still catching typos per-country format.
// Source: ITU E.164 national numbering plans (common mobile/landline ranges).

export const COUNTRIES = [
  { iso: 'AF', name: "Afghanistan", dial: '93', len: [9, 9] },
  { iso: 'AL', name: "Albania", dial: '355', len: [8, 9] },
  { iso: 'DZ', name: "Algeria", dial: '213', len: [8, 9] },
  { iso: 'AS', name: "American Samoa", dial: '1684', len: [10, 10] },
  { iso: 'AD', name: "Andorra", dial: '376', len: [6, 6] },
  { iso: 'AO', name: "Angola", dial: '244', len: [9, 9] },
  { iso: 'AI', name: "Anguilla", dial: '1264', len: [10, 10] },
  { iso: 'AG', name: "Antigua and Barbuda", dial: '1268', len: [10, 10] },
  { iso: 'AR', name: "Argentina", dial: '54', len: [10, 10] },
  { iso: 'AM', name: "Armenia", dial: '374', len: [8, 8] },
  { iso: 'AW', name: "Aruba", dial: '297', len: [7, 7] },
  { iso: 'AU', name: "Australia", dial: '61', len: [9, 9] },
  { iso: 'AT', name: "Austria", dial: '43', len: [7, 11] },
  { iso: 'AZ', name: "Azerbaijan", dial: '994', len: [9, 9] },
  { iso: 'BS', name: "Bahamas", dial: '1242', len: [10, 10] },
  { iso: 'BH', name: "Bahrain", dial: '973', len: [8, 8] },
  { iso: 'BD', name: "Bangladesh", dial: '880', len: [8, 10] },
  { iso: 'BB', name: "Barbados", dial: '1246', len: [10, 10] },
  { iso: 'BY', name: "Belarus", dial: '375', len: [9, 9] },
  { iso: 'BE', name: "Belgium", dial: '32', len: [8, 9] },
  { iso: 'BZ', name: "Belize", dial: '501', len: [7, 7] },
  { iso: 'BJ', name: "Benin", dial: '229', len: [8, 8] },
  { iso: 'BM', name: "Bermuda", dial: '1441', len: [10, 10] },
  { iso: 'BT', name: "Bhutan", dial: '975', len: [7, 8] },
  { iso: 'BO', name: "Bolivia", dial: '591', len: [8, 8] },
  { iso: 'BA', name: "Bosnia and Herzegovina", dial: '387', len: [8, 8] },
  { iso: 'BW', name: "Botswana", dial: '267', len: [7, 8] },
  { iso: 'BR', name: "Brazil", dial: '55', len: [10, 11] },
  { iso: 'BN', name: "Brunei", dial: '673', len: [7, 7] },
  { iso: 'BG', name: "Bulgaria", dial: '359', len: [7, 9] },
  { iso: 'BF', name: "Burkina Faso", dial: '226', len: [8, 8] },
  { iso: 'BI', name: "Burundi", dial: '257', len: [8, 8] },
  { iso: 'KH', name: "Cambodia", dial: '855', len: [8, 9] },
  { iso: 'CM', name: "Cameroon", dial: '237', len: [9, 9] },
  { iso: 'CA', name: "Canada", dial: '1', len: [10, 10] },
  { iso: 'CV', name: "Cape Verde", dial: '238', len: [7, 7] },
  { iso: 'KY', name: "Cayman Islands", dial: '1345', len: [10, 10] },
  { iso: 'CF', name: "Central African Republic", dial: '236', len: [8, 8] },
  { iso: 'TD', name: "Chad", dial: '235', len: [8, 8] },
  { iso: 'CL', name: "Chile", dial: '56', len: [9, 9] },
  { iso: 'CN', name: "China", dial: '86', len: [10, 11] },
  { iso: 'CO', name: "Colombia", dial: '57', len: [10, 10] },
  { iso: 'KM', name: "Comoros", dial: '269', len: [7, 7] },
  { iso: 'CG', name: "Congo", dial: '242', len: [9, 9] },
  { iso: 'CD', name: "Congo (DRC)", dial: '243', len: [9, 9] },
  { iso: 'CK', name: "Cook Islands", dial: '682', len: [5, 5] },
  { iso: 'CR', name: "Costa Rica", dial: '506', len: [8, 8] },
  { iso: 'CI', name: "Ivory Coast", dial: '225', len: [8, 10] },
  { iso: 'HR', name: "Croatia", dial: '385', len: [8, 9] },
  { iso: 'CU', name: "Cuba", dial: '53', len: [6, 8] },
  { iso: 'CW', name: "Curacao", dial: '599', len: [7, 7] },
  { iso: 'CY', name: "Cyprus", dial: '357', len: [8, 8] },
  { iso: 'CZ', name: "Czech Republic", dial: '420', len: [9, 9] },
  { iso: 'DK', name: "Denmark", dial: '45', len: [8, 8] },
  { iso: 'DJ', name: "Djibouti", dial: '253', len: [8, 8] },
  { iso: 'DM', name: "Dominica", dial: '1767', len: [10, 10] },
  { iso: 'DO', name: "Dominican Republic", dial: '1809', len: [10, 10] },
  { iso: 'EC', name: "Ecuador", dial: '593', len: [9, 9] },
  { iso: 'EG', name: "Egypt", dial: '20', len: [9, 10] },
  { iso: 'SV', name: "El Salvador", dial: '503', len: [8, 8] },
  { iso: 'GQ', name: "Equatorial Guinea", dial: '240', len: [9, 9] },
  { iso: 'ER', name: "Eritrea", dial: '291', len: [7, 7] },
  { iso: 'EE', name: "Estonia", dial: '372', len: [7, 8] },
  { iso: 'SZ', name: "Eswatini", dial: '268', len: [8, 8] },
  { iso: 'ET', name: "Ethiopia", dial: '251', len: [9, 9] },
  { iso: 'FJ', name: "Fiji", dial: '679', len: [7, 7] },
  { iso: 'FI', name: "Finland", dial: '358', len: [5, 12] },
  { iso: 'FR', name: "France", dial: '33', len: [9, 9] },
  { iso: 'GF', name: "French Guiana", dial: '594', len: [9, 9] },
  { iso: 'PF', name: "French Polynesia", dial: '689', len: [6, 6] },
  { iso: 'GA', name: "Gabon", dial: '241', len: [7, 8] },
  { iso: 'GM', name: "Gambia", dial: '220', len: [7, 7] },
  { iso: 'GE', name: "Georgia", dial: '995', len: [9, 9] },
  { iso: 'DE', name: "Germany", dial: '49', len: [6, 11] },
  { iso: 'GH', name: "Ghana", dial: '233', len: [9, 9] },
  { iso: 'GI', name: "Gibraltar", dial: '350', len: [8, 8] },
  { iso: 'GR', name: "Greece", dial: '30', len: [10, 10] },
  { iso: 'GL', name: "Greenland", dial: '299', len: [6, 6] },
  { iso: 'GD', name: "Grenada", dial: '1473', len: [10, 10] },
  { iso: 'GP', name: "Guadeloupe", dial: '590', len: [9, 9] },
  { iso: 'GU', name: "Guam", dial: '1671', len: [10, 10] },
  { iso: 'GT', name: "Guatemala", dial: '502', len: [8, 8] },
  { iso: 'GN', name: "Guinea", dial: '224', len: [9, 9] },
  { iso: 'GW', name: "Guinea-Bissau", dial: '245', len: [7, 7] },
  { iso: 'GY', name: "Guyana", dial: '592', len: [7, 7] },
  { iso: 'HT', name: "Haiti", dial: '509', len: [8, 8] },
  { iso: 'HN', name: "Honduras", dial: '504', len: [8, 8] },
  { iso: 'HK', name: "Hong Kong", dial: '852', len: [8, 8] },
  { iso: 'HU', name: "Hungary", dial: '36', len: [8, 9] },
  { iso: 'IS', name: "Iceland", dial: '354', len: [7, 7] },
  { iso: 'IN', name: "India", dial: '91', len: [10, 10] },
  { iso: 'ID', name: "Indonesia", dial: '62', len: [9, 11] },
  { iso: 'IR', name: "Iran", dial: '98', len: [10, 10] },
  { iso: 'IQ', name: "Iraq", dial: '964', len: [9, 10] },
  { iso: 'IE', name: "Ireland", dial: '353', len: [7, 9] },
  { iso: 'IL', name: "Israel", dial: '972', len: [8, 9] },
  { iso: 'IT', name: "Italy", dial: '39', len: [9, 10] },
  { iso: 'JM', name: "Jamaica", dial: '1876', len: [10, 10] },
  { iso: 'JP', name: "Japan", dial: '81', len: [9, 10] },
  { iso: 'JO', name: "Jordan", dial: '962', len: [8, 9] },
  { iso: 'KZ', name: "Kazakhstan", dial: '7', len: [10, 10] },
  { iso: 'KE', name: "Kenya", dial: '254', len: [9, 9] },
  { iso: 'KI', name: "Kiribati", dial: '686', len: [5, 8] },
  { iso: 'XK', name: "Kosovo", dial: '383', len: [8, 8] },
  { iso: 'KW', name: "Kuwait", dial: '965', len: [8, 8] },
  { iso: 'KG', name: "Kyrgyzstan", dial: '996', len: [9, 9] },
  { iso: 'LA', name: "Laos", dial: '856', len: [8, 10] },
  { iso: 'LV', name: "Latvia", dial: '371', len: [8, 8] },
  { iso: 'LB', name: "Lebanon", dial: '961', len: [8, 8] },
  { iso: 'LS', name: "Lesotho", dial: '266', len: [8, 8] },
  { iso: 'LR', name: "Liberia", dial: '231', len: [7, 8] },
  { iso: 'LY', name: "Libya", dial: '218', len: [9, 9] },
  { iso: 'LI', name: "Liechtenstein", dial: '423', len: [7, 7] },
  { iso: 'LT', name: "Lithuania", dial: '370', len: [8, 8] },
  { iso: 'LU', name: "Luxembourg", dial: '352', len: [4, 9] },
  { iso: 'MO', name: "Macau", dial: '853', len: [8, 8] },
  { iso: 'MG', name: "Madagascar", dial: '261', len: [9, 9] },
  { iso: 'MW', name: "Malawi", dial: '265', len: [7, 9] },
  { iso: 'MY', name: "Malaysia", dial: '60', len: [8, 10] },
  { iso: 'MV', name: "Maldives", dial: '960', len: [7, 7] },
  { iso: 'ML', name: "Mali", dial: '223', len: [8, 8] },
  { iso: 'MT', name: "Malta", dial: '356', len: [8, 8] },
  { iso: 'MH', name: "Marshall Islands", dial: '692', len: [7, 7] },
  { iso: 'MQ', name: "Martinique", dial: '596', len: [9, 9] },
  { iso: 'MR', name: "Mauritania", dial: '222', len: [8, 8] },
  { iso: 'MU', name: "Mauritius", dial: '230', len: [7, 8] },
  { iso: 'YT', name: "Mayotte", dial: '262', len: [9, 9] },
  { iso: 'MX', name: "Mexico", dial: '52', len: [10, 10] },
  { iso: 'FM', name: "Micronesia", dial: '691', len: [7, 7] },
  { iso: 'MD', name: "Moldova", dial: '373', len: [8, 8] },
  { iso: 'MC', name: "Monaco", dial: '377', len: [8, 9] },
  { iso: 'MN', name: "Mongolia", dial: '976', len: [8, 8] },
  { iso: 'ME', name: "Montenegro", dial: '382', len: [8, 8] },
  { iso: 'MS', name: "Montserrat", dial: '1664', len: [10, 10] },
  { iso: 'MA', name: "Morocco", dial: '212', len: [9, 9] },
  { iso: 'MZ', name: "Mozambique", dial: '258', len: [8, 9] },
  { iso: 'MM', name: "Myanmar", dial: '95', len: [7, 9] },
  { iso: 'NA', name: "Namibia", dial: '264', len: [9, 9] },
  { iso: 'NR', name: "Nauru", dial: '674', len: [7, 7] },
  { iso: 'NP', name: "Nepal", dial: '977', len: [8, 10] },
  { iso: 'NL', name: "Netherlands", dial: '31', len: [9, 9] },
  { iso: 'NC', name: "New Caledonia", dial: '687', len: [6, 6] },
  { iso: 'NZ', name: "New Zealand", dial: '64', len: [8, 10] },
  { iso: 'NI', name: "Nicaragua", dial: '505', len: [8, 8] },
  { iso: 'NE', name: "Niger", dial: '227', len: [8, 8] },
  { iso: 'NG', name: "Nigeria", dial: '234', len: [8, 10] },
  { iso: 'MK', name: "North Macedonia", dial: '389', len: [8, 8] },
  { iso: 'MP', name: "Northern Mariana Islands", dial: '1670', len: [10, 10] },
  { iso: 'NO', name: "Norway", dial: '47', len: [8, 8] },
  { iso: 'OM', name: "Oman", dial: '968', len: [8, 8] },
  { iso: 'PK', name: "Pakistan", dial: '92', len: [9, 10] },
  { iso: 'PW', name: "Palau", dial: '680', len: [7, 7] },
  { iso: 'PS', name: "Palestine", dial: '970', len: [8, 9] },
  { iso: 'PA', name: "Panama", dial: '507', len: [7, 8] },
  { iso: 'PG', name: "Papua New Guinea", dial: '675', len: [7, 8] },
  { iso: 'PY', name: "Paraguay", dial: '595', len: [9, 9] },
  { iso: 'PE', name: "Peru", dial: '51', len: [9, 9] },
  { iso: 'PH', name: "Philippines", dial: '63', len: [10, 10] },
  { iso: 'PL', name: "Poland", dial: '48', len: [9, 9] },
  { iso: 'PT', name: "Portugal", dial: '351', len: [9, 9] },
  { iso: 'PR', name: "Puerto Rico", dial: '1787', len: [10, 10] },
  { iso: 'QA', name: "Qatar", dial: '974', len: [8, 8] },
  { iso: 'RE', name: "Reunion", dial: '262', len: [9, 9] },
  { iso: 'RO', name: "Romania", dial: '40', len: [9, 9] },
  { iso: 'RU', name: "Russia", dial: '7', len: [10, 10] },
  { iso: 'RW', name: "Rwanda", dial: '250', len: [9, 9] },
  { iso: 'BL', name: "Saint Barthelemy", dial: '590', len: [9, 9] },
  { iso: 'SH', name: "Saint Helena", dial: '290', len: [4, 4] },
  { iso: 'KN', name: "Saint Kitts and Nevis", dial: '1869', len: [10, 10] },
  { iso: 'LC', name: "Saint Lucia", dial: '1758', len: [10, 10] },
  { iso: 'MF', name: "Saint Martin", dial: '590', len: [9, 9] },
  { iso: 'PM', name: "Saint Pierre and Miquelon", dial: '508', len: [6, 6] },
  { iso: 'VC', name: "Saint Vincent and the Grenadines", dial: '1784', len: [10, 10] },
  { iso: 'WS', name: "Samoa", dial: '685', len: [5, 7] },
  { iso: 'SM', name: "San Marino", dial: '378', len: [6, 10] },
  { iso: 'ST', name: "Sao Tome and Principe", dial: '239', len: [7, 7] },
  { iso: 'SA', name: "Saudi Arabia", dial: '966', len: [8, 9] },
  { iso: 'SN', name: "Senegal", dial: '221', len: [9, 9] },
  { iso: 'RS', name: "Serbia", dial: '381', len: [8, 9] },
  { iso: 'SC', name: "Seychelles", dial: '248', len: [7, 7] },
  { iso: 'SL', name: "Sierra Leone", dial: '232', len: [8, 8] },
  { iso: 'SG', name: "Singapore", dial: '65', len: [8, 8] },
  { iso: 'SK', name: "Slovakia", dial: '421', len: [9, 9] },
  { iso: 'SI', name: "Slovenia", dial: '386', len: [8, 8] },
  { iso: 'SB', name: "Solomon Islands", dial: '677', len: [7, 7] },
  { iso: 'SO', name: "Somalia", dial: '252', len: [7, 9] },
  { iso: 'ZA', name: "South Africa", dial: '27', len: [9, 9] },
  { iso: 'KR', name: "South Korea", dial: '82', len: [8, 10] },
  { iso: 'SS', name: "South Sudan", dial: '211', len: [9, 9] },
  { iso: 'ES', name: "Spain", dial: '34', len: [9, 9] },
  { iso: 'LK', name: "Sri Lanka", dial: '94', len: [9, 9] },
  { iso: 'SD', name: "Sudan", dial: '249', len: [9, 9] },
  { iso: 'SR', name: "Suriname", dial: '597', len: [6, 7] },
  { iso: 'SE', name: "Sweden", dial: '46', len: [7, 9] },
  { iso: 'CH', name: "Switzerland", dial: '41', len: [9, 9] },
  { iso: 'SY', name: "Syria", dial: '963', len: [8, 9] },
  { iso: 'TW', name: "Taiwan", dial: '886', len: [9, 9] },
  { iso: 'TJ', name: "Tajikistan", dial: '992', len: [9, 9] },
  { iso: 'TZ', name: "Tanzania", dial: '255', len: [9, 9] },
  { iso: 'TH', name: "Thailand", dial: '66', len: [8, 9] },
  { iso: 'TL', name: "Timor-Leste", dial: '670', len: [7, 8] },
  { iso: 'TG', name: "Togo", dial: '228', len: [8, 8] },
  { iso: 'TO', name: "Tonga", dial: '676', len: [5, 7] },
  { iso: 'TT', name: "Trinidad and Tobago", dial: '1868', len: [10, 10] },
  { iso: 'TN', name: "Tunisia", dial: '216', len: [8, 8] },
  { iso: 'TR', name: "Turkey", dial: '90', len: [10, 10] },
  { iso: 'TM', name: "Turkmenistan", dial: '993', len: [8, 8] },
  { iso: 'TC', name: "Turks and Caicos Islands", dial: '1649', len: [10, 10] },
  { iso: 'TV', name: "Tuvalu", dial: '688', len: [5, 6] },
  { iso: 'UG', name: "Uganda", dial: '256', len: [9, 9] },
  { iso: 'UA', name: "Ukraine", dial: '380', len: [9, 9] },
  { iso: 'AE', name: "United Arab Emirates", dial: '971', len: [8, 9] },
  { iso: 'GB', name: "United Kingdom", dial: '44', len: [9, 10] },
  { iso: 'US', name: "United States", dial: '1', len: [10, 10] },
  { iso: 'UY', name: "Uruguay", dial: '598', len: [8, 8] },
  { iso: 'UZ', name: "Uzbekistan", dial: '998', len: [9, 9] },
  { iso: 'VU', name: "Vanuatu", dial: '678', len: [5, 7] },
  { iso: 'VA', name: "Vatican City", dial: '39', len: [9, 10] },
  { iso: 'VE', name: "Venezuela", dial: '58', len: [10, 10] },
  { iso: 'VN', name: "Vietnam", dial: '84', len: [9, 10] },
  { iso: 'VG', name: "British Virgin Islands", dial: '1284', len: [10, 10] },
  { iso: 'VI', name: "U.S. Virgin Islands", dial: '1340', len: [10, 10] },
  { iso: 'WF', name: "Wallis and Futuna", dial: '681', len: [6, 6] },
  { iso: 'YE', name: "Yemen", dial: '967', len: [7, 9] },
  { iso: 'ZM', name: "Zambia", dial: '260', len: [9, 9] },
  { iso: 'ZW', name: "Zimbabwe", dial: '263', len: [9, 9] }
];

export const DEFAULT_COUNTRY = 'LB';

export function findCountry(iso) {
  return COUNTRIES.find((c) => c.iso === iso) || null;
}

// Remove everything but digits, then drop leading trunk zeros.
export function stripTrunkZero(national) {
  return String(national || '').replace(/\D/g, '').replace(/^0+/, '');
}

// Validate the national part against the country's NSN length range.
export function validateNationalNumber(country, national) {
  const digits = stripTrunkZero(national);
  const [min, max] = country?.len || [4, 15];
  return { ok: digits.length >= min && digits.length <= max, digits, min, max };
}

// Build the E.164 representation used across orders, pixels and emails.
export function toE164(country, national) {
  const digits = stripTrunkZero(national);
  return `+${country.dial}${digits}`;
}
